### ISSUE TITLE
Add custom k9s views

### ISSUE THREAD

**Issue by hammady** [hammady/ohmyk8s#3]
Add the following in `.bashrc` to work with k9s [v0.24.15+](https://github.com/derailed/k9s/releases/tag/v0.24.15) in case there are custom configuration or views:
```bash
export XDG_CONFIG_HOME=`xdg-user-dir` # or $HOME if xdg is not installed
```
Below is a custom view to show age in the begining:
```yaml
# $XDG_CONFIG_HOME/k9s/views.yml
k9s:
  views:
    v1/pods:
      columns:
        - AGE
        - NAMESPACE
        - NAME
        - RESTARTS
        - STATUS
        - READY
        - CPU
        - "%CPU/R"
        - "%CPU/L"
        - MEM
        - "%MEM/R"
        - "%MEM/L"
        - PF
        - IP
        - NODE
    v1/services:
      columns:
        - AGE
        - NAMESPACE
        - NAME
        - PORTS
        - TYPE
        - CLUSTER-IP
        - EXTERNAL-IP
    apps/v1/deployments:
      columns:
        - AGE
        - NAMESPACE
        - NAME
        - READY
        - UP-TO-DATE
        - AVAILABLE
    apps/v1/statefulsets:
      columns:
        - AGE
        - NAMESPACE
        - NAME
        - READY
        - SERVICE
    apps/v1/daemonsets:
      columns:
        - AGE
        - NAMESPACE
        - NAME
        - DESIRED
        - CURRENT
        - READY
        - UP-TO-DATE
        - AVAILABLE
    v1/nodes:
      columns:
        - AGE
        - NAME
        - STATUS
        - PODS
        - CPU
        - "%CPU"
        - CPU/A
        - MEM
        - "%MEM"
        - MEM/A
        - VERSION
        - ROLE
    v1/persistentvolumeclaims:
      columns:
        - AGE
        - NAMESPACE
        - NAME
        - STATUS
        - VOLUME
        - CAPACITY
        - ACCESS
        - MODES
        - STORAGECLASS
    v1/persistentvolumes:
      columns:
        - AGE
        - NAME
        - CAPACITY
        - ACCESS MODES
        - RECLAIM POLICY
        - STATUS
        - CLAIM
        - STORAGECLASS
        - REASON
    v1/configmaps:
      columns:
        - AGE
        - NAMESPACE
        - NAME
        - DATA
    v1/secrets:
      columns:
        - AGE
        - NAMESPACE
        - NAME
        - DATA
        - TYPE
    batch/v1beta1/cronjobs:
      columns:
        - AGE
        - NAMESPACE
        - NAME
        - SUSPEND
        - SCHEDULE
        - LAST_SCHEDULE
        - ACTIVE
    batch/v1/jobs:
      columns:
        - AGE
        - NAMESPACE
        - NAME
        - COMPLETIONS
        - DURATION
    v1/events:
      columns:
        - AGE
        - COUNT
        - TYPE
        - NAMESPACE
        - NAME
        - REASON
        - SOURCE
```

**Comment by maboelnour** [comment]
`k9s info` to see where `k9s` is loading it's configs, then inside `views.yaml` file:

```yaml
views:
  v1/pods:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - RESTARTS
      - STATUS
      - READY
      - CPU
      - "%CPU/R"
      - "%CPU/L"
      - MEM
      - "%MEM/R"
      - "%MEM/L"
      - PF
      - IP
      - NODE
  v1/services:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - PORTS
      - TYPE
      - CLUSTER-IP
      - EXTERNAL-IP
  apps/v1/deployments:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - READY
      - UP-TO-DATE
      - AVAILABLE
  apps/v1/statefulsets:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - READY
      - SERVICE
  apps/v1/replicasets:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - READY
      - SERVICE
  apps/v1/daemonsets:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - DESIRED
      - CURRENT
      - READY
      - UP-TO-DATE
      - AVAILABLE
  v1/nodes:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAME
      - STATUS
      - PODS
      - CPU
      - "%CPU"
      - CPU/A
      - MEM
      - "%MEM"
      - MEM/A
      - VERSION
      - ROLE
  v1/persistentvolumeclaims:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - STATUS
      - VOLUME
      - CAPACITY
      - ACCESS
      - MODES
      - STORAGECLASS
  v1/persistentvolumes:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAME
      - CAPACITY
      - ACCESS MODES
      - RECLAIM POLICY
      - STATUS
      - CLAIM
      - STORAGECLASS
      - REASON
  v1/configmaps:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - DATA
  v1/secrets:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - DATA
      - TYPE
  batch/v1/cronjobs:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - SUSPEND
      - SCHEDULE
      - LAST_SCHEDULE
      - ACTIVE
  batch/v1/jobs:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - COMPLETIONS
      - DURATION
  v1/events:
    sortColumn: AGE:asc
    columns:
      - AGE
      - COUNT
      - TYPE
      - NAMESPACE
      - NAME
      - REASON
      - SOURCE
  networking.k8s.io/v1/ingresses:
    sortColumn: AGE:asc
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - HOSTS
      - ADDRESS
      - PORTS
      - BACKEND

```
